---
plugins:
  - id: mygenerator
    type: generate
    output: myjson
    count: 100000
    record:
      test: '{"message":"testmessage"}'
  - id: myjson
    type: json
    field: test
    output: mystackdriver
  - id: mystackdriver
    type: stackdriver
    project_id: ***REMOVED***
    credentials: >-
      {
        "sample":"creds"
      }
