---
plugins:
  - id: mygenerator
    type: generate
    count: 100
    output: mylimiter
    record:
      test: '{"message":"testmessage"}'
  - id: mylimiter
    type: rate_limit
    rate: 100
    output: myjson
  - id: myjson
    type: json
    buffer_size: 1
    field: test
    output: mylogger
  - id: mylogger
    buffer_size: 1
    type: logger
    level: info
