version: 2.1

orbs:
  win: circleci/windows@2.4.0
  codecov: codecov/codecov@1.0.2

executors:
  golang:
    docker:
      - image: circleci/golang:1.13
  mac:
    macos:
      xcode: 11.4.1

jobs:

  build:
    executor: golang
    steps:
      - checkout

      - run:
          name: Get dependencies
          command: go get -v -t -d ./...
      - run:
          name: Build
          command: go build -v -o ./main.out ./
      - run:
          name: Install golangci-lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
      - run:
          name: Lint
          command: golangci-lint run

  test-linux:
    executor: golang

    steps:
      - checkout
      - run:
          name: Unit tests
          command: |
            go test -race -v -coverprofile coverage.txt -coverpkg ./... ./...
      - codecov/upload:
          file: ./coverage.txt

  test-macos:
    executor: mac

    steps:
      - checkout
      - run:
          name: Download golang
          command: curl -SL https://dl.google.com/go/go1.13.11.darwin-amd64.tar.gz -o go1.13.11.darwin-amd64.tar.gz
      - run:
          name: Extract golang
          command: tar -C ~ -xzf go1.13.11.darwin-amd64.tar.gz
      - run:
          name: Add golang to path
          command: echo 'export PATH=~/go/bin:$PATH' >> $BASH_ENV
      - run:
          name: Unit tests
          command: go test -race -v ./...

  test-windows:
    executor: win/default

    steps:
      - checkout
      - run:
          name: Upgrade golang
          shell: powershell.exe
          command: choco upgrade golang --version=1.13
      - run:
          name: Install GCC
          shell: powershell.exe
          command: choco install mingw
      - run:
          name: Get dependencies
          shell: powershell.exe
          command: go get -v -t -d ./...
      - run:
          name: Unit tests
          shell: powershell.exe
          command: go test -race -v ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-linux
      - test-macos
      - test-windows
