version: 2.1

orbs:
  win: circleci/windows@2.4.0

executors:
  golang:
    docker:
      - image: circleci/golang:1.13
  mac:
    macos:
      xcode: 11.4.1

jobs:

  build:
    executor: golang
    steps:
      - checkout

      - run: 
          name: Get dependencies
          command: go get -v -t -d ./...
      - run: 
          name: Build
          command: go build -v -o ./main.out ./

  test-linux:
    executor: golang

    steps:
      - checkout
      - run: 
          name: Unit tests
          command: go test -race -v ./...

  test-macos:
    executor: mac
    
    steps:
      - checkout
      - run: 
          name: Download golang
          command: curl -SL https://dl.google.com/go/go1.13.11.darwin-amd64.tar.gz -o go1.13.11.darwin-amd64.tar.gz
      - run:
          name: Extract golang
          command: tar -C ~ -xzf go1.13.11.darwin-amd64.tar.gz
      - run:
          name: Add golang to path
          command: echo 'export PATH=~/go/bin:$PATH' >> $BASH_ENV
      - run:
          name: Unit tests
          command: go test -race -v ./...

  test-windows:
    executor: win/default

    steps:
      - checkout
      - run:
          name: Upgrade golang
          shell: powershell.exe
          command: choco upgrade golang --version=1.13
      - run:
          name: Install GCC
          shell: powershell.exe
          command: choco install mingw      
      - run:
          name: Unit tests
          shell: powershell.exe
          command: go test -race -v ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-linux
      - test-macos
      - test-windows