# https://circleci.com/docs/2.0/language-go/ 
version: 2
jobs:
  build:
    docker:      
      - image: circleci/golang:1.13
    
    working_directory: /go/src/github.com/bluemedora/bplogagent
    steps:
      - checkout # check out source code to working directory

      - run: go get -v -t -d ./...
      - run: go test -race -v ./...
      - run: go build -v -o ./main.out ./