version: 2.1

orbs:
  win: circleci/windows@2.4.0

executors:
  golang:
    docker:
      - image: circleci/golang:1.13
  mac:
    macos:
      xcode: 11.4.1

jobs:

  build:
    executor: golang
    steps:
      - checkout

      - run: go get -v -t -d ./...      
      - run: go build -v -o ./main.out ./

  test-linux:
    executor: golang

    steps:
      - checkout
      - run: go get -v -t -d ./...      
      - run: go test -race -v ./...

  test-macos:
    executor: mac

    steps:
      - checkout
      - run: 
          name: Download golang
          command: curl -SL https://dl.google.com/go/go1.13.11.darwin-amd64.tar.gz -o go1.13.11.darwin-amd64.tar.gz
      - run:          
          name: Extract golang
          command: tar -C /usr/local -xzf go1.13.11.darwin-amd64.tar.gz
      - run: 
          name: Add golang to path
          command: export PATH=$PATH:/usr/local/go/bin
      - run: 
          name: Refresh profile
          command: source ~/.profile
      - run: 
          name: Get dependencies
          command: go get -v -t -d ./...      
      - run: 
          name: Run tests
          command: go test -race -v ./...

  test-windows:
    executor: win/default
      
    steps:
      - checkout      
      - run:
          name: Upgrade golang
          shell: powershell.exe
          command: choco upgrade golang --version=1.13
      - run:
          name: Get
          shell: powershell.exe
          command: go get -v -t -d ./...
      - run:
          name: Unit tests
          shell: powershell.exe
          command: go test ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-linux
      - test-macos
      - test-windows