plugins:
  - id: fileinput
    type: file_input
    include: ["stream*.log"]
    output: google_cloud

  - id: google_cloud
    type: google_cloud_output
    project_id: bplogagent-benchmark
    # credentials found automatically on gce instance

database_file: /home/djaglowski/benchmark/logagent.db